-- Updated schema.sql portion
DROP TABLE IF EXISTS CART;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS ACCOUNT;

CREATE TABLE ACCOUNT
(
    ID   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE PRODUCT
(
    ID    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME  VARCHAR(255) NOT NULL,
    PRICE DECIMAL(10, 2)
);

CREATE TABLE CART
(
    ID         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USER_ID    INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    QUANTITY   INT NOT NULL DEFAULT 1,
    CREATED_AT TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

-- Updated sample data
INSERT INTO PRODUCT (ID, NAME, PRICE)
VALUES (1, 'Gaming Laptop', 1299.99),
       (2, 'Wireless Headphones', 199.99),
       (3, 'Smart Watch', 249.99),
       (4, 'Smart Fridge', 249.99),
       (5, 'Smart Home', 249.99),
       (6, 'Smart Oven', 249.99),
       (7, 'Smart Car', 249.99),
       (8, 'Smart Dog', 249.99);

INSERT INTO ACCOUNT (ID, NAME)
VALUES (1, 'Jane Smith'),
       (2, 'John Smith'),
       (3, 'Alice Johnson');

INSERT INTO CART (USER_ID, PRODUCT_ID, QUANTITY)
VALUES
    -- Jane's cart
    (1, 1, 1),
    (1, 2, 1),
    (1, 3, 1),
    (1, 4, 1),
    (1, 5, 1),
    (1, 6, 1),
    (1, 7, 1),
    (1, 8, 1),
    -- John's cart
    (2, 1, 1),
    (2, 2, 1),
    -- Alice's cart
    (3, 1, 1)
